#!/bin/bash
total 20
-rwxrwxrwx 1 root root 16 Feb  8 03:23 0-current_working_directory
-rwxr-xr-x 1 root root 15 Feb  8 03:35 1-listit
-rwxr-xr-x 1 root root 15 Feb  8 03:41 2-bring_me_home
-rwxr-xr-x 1 root root 17 Feb  8 03:51 3-listfiles
-rw-r--r-- 1 root root 14 Feb  8 03:23 README.md
